### ISSUE TITLE
Communication issue with XRay Daemon

### ISSUE THREAD

**Issue by awsimaya** [aws-samples/aws-xray-kubernetes#6]
### Following the instructions in the repo and the blog post results in some issues. Not sure if it's only in my environment.

The services (service-a and service-b) don't start. See below. 

```
NAMESPACE     NAME                             READY   STATUS             RESTARTS   AGE
default       pod/service-a-8699d4bf68-65f5x   0/1     CrashLoopBackOff   11         32m
default       pod/service-a-8699d4bf68-hh2l5   0/1     CrashLoopBackOff   11         32m
default       pod/service-b-86564fd46b-b4ft8   0/1     CrashLoopBackOff   11         32m
default       pod/service-b-86564fd46b-kvplc   0/1     CrashLoopBackOff   11         32m
```
```
demo-app ➤ kubectl logs  pod/service-a-8699d4bf68-65f5x
/usr/src/app/node_modules/aws-xray-sdk-core/lib/daemon_config.js:26
    throw new Error('Invalid Daemon Address. You must specify an ip and port.');
    ^

Error: Invalid Daemon Address. You must specify an ip and port.
    at processAddress (/usr/src/app/node_modules/aws-xray-sdk-core/lib/daemon_config.js:26:11)
    at Object.<anonymous> (/usr/src/app/node_modules/aws-xray-sdk-core/lib/daemon_config.js:62:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/node_modules/aws-xray-sdk-core/lib/segment_emitter.js:105:17)
```

There seems to be an issue communicating with the X-Ray daemonset. However, the it seems to be running properly.

```
demo-app ➤ kubectl logs pod/xray-daemon-5v7zt
2020-03-27T14:53:29Z [Info] Initializing AWS X-Ray daemon 2.1.3
2020-03-27T14:53:29Z [Info] Using buffer memory limit of 76 MB
2020-03-27T14:53:29Z [Info] 1216 segment buffers allocated
2020-03-27T14:53:29Z [Info] Using region: us-east-2
```

#### Another recommendation I have is to update the K8s deployment template to v1 instead of v1beta so we can use selectors

**Comment by ckassen** [comment]
With the recent updates to the daemon itself, does this issue still persist? I can not reproduce it so far.

**Comment by awsimaya** [comment]
This happens to be a bug in the X-Ray SDK for .NET. Closing this issue.

**Comment by ckassen** [comment]
Cool. Thanks for the update.
